
ALTER TABLE DESCUENTO
DROP CONSTRAINT FK_producto ;

ALTER TABLE PRODUCTO
DROP CONSTRAINT FK_nombre_servicio;

ALTER TABLE CONSUMO
DROP CONSTRAINT FK_reserva;

ALTER TABLE CONSUMO
DROP CONSTRAINT FK_Servicio;

ALTER TABLE TIENE_UTENSILIO 
DROP CONSTRAINT FK_id_Reserva;

ALTER TABLE TIENE_UTENSILIO
DROP CONSTRAINT FK_Id_Utensilio;

ALTER TABLE RESERVA
DROP CONSTRAINT FK_documento_Cliente;

ALTER TABLE RESERVA
DROP CONSTRAINT FK_codigo_Habitacion;

ALTER TABLE RESERVA_DE_SERVICIO
DROP CONSTRAINT FK_nombre_Servicio_RDS;

ALTER TABLE RESERVA_DE_SERVICIO
DROP CONSTRAINT FK_id_Reserva_RDS;

ALTER TABLE PLANES_DISPONIBLES
DROP CONSTRAINT FK_nombre_Hotel_PD;

ALTER TABLE HABITACION
DROP CONSTRAINT FK_nombre_Hotel_H;

ALTER TABLE HABITACION
DROP CONSTRAINT FK_nombre_Tipo_Habitacion_H;

ALTER TABLE USUARIO
DROP CONSTRAINT FK_nombre_Rol_Usuario;

ALTER TABLE USUARIO
DROP CONSTRAINT FK_nombre_Hotel_Usuario;

ALTER TABLE HABITACION_HOTEL
DROP CONSTRAINT FK_nombre_Hotel_HH;

ALTER TABLE HABITACION_HOTEL
DROP CONSTRAINT FK_codigo_Habitacion_HH;

ALTER TABLE ACOMPANIANTE_RESERVA
DROP CONSTRAINT FK_documento_Acompaniante;

ALTER TABLE ACOMPANIANTE_RESERVA
DROP CONSTRAINT FK_id_Reserva_AR;

ALTER TABLE PRODUCTOS_CONSUMIDOS
DROP CONSTRAINT FK_id_Consumo_PC;

ALTER TABLE PRODUCTOS_CONSUMIDOS
DROP CONSTRAINT FK_nombre_Producto_PC;

ALTER TABLE SERVICIO_TIPO_SERVICIO
DROP CONSTRAINT FK_nombre_Servicio_STS;

ALTER TABLE SERVICIO_TIPO_SERVICIO
DROP CONSTRAINT FK_id_Tipo_Servicio_STS;

ALTER TABLE TIPO_HABITACION_HOTEL
DROP CONSTRAINT FK_nombre_Tipo_THH;

ALTER TABLE TIPO_HABITACION_HOTEL
DROP CONSTRAINT FK_nombre_Hotel_THH;

DROP TABLE PRODUCTO;
DROP TABLE DESCUENTO;
DROP TABLE UTENSILIO;
DROP TABLE CONSUMO;
DROP TABLE TIENE_UTENSILIO;
DROP TABLE RESERVA;
DROP TABLE SERVICIO;
DROP TABLE RESERVA_DE_SERVICIO;
DROP TABLE TIPO_SERVICIO;
DROP TABLE PLANES_DISPONIBLES;
DROP TABLE ACOMPANIANTE;
DROP TABLE HOTEL;
DROP TABLE TIPO_HABITACION;
DROP TABLE HABITACION;
DROP TABLE USUARIO ;
DROP TABLE ROL_USUARIO ;
DROP TABLE HABITACION_HOTEL;
DROP TABLE ACOMPANIANTE_RESERVA;
DROP TABLE PRODUCTOS_CONSUMIDOS;
DROP TABLE SERVICIO_TIPO_SERVICIO;
DROP TABLE TIPO_HABITACION_HOTEL;